name: "Create zim archive"

on:
  schedule:
    - cron: "0 0 1 * *" # run every first of month
  workflow_dispatch:
  push:
    
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      date-tag: ${{ steps.setup.outputs.date-tag }}
      matrix: ${{ steps.setup.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: setup
        run: |
          echo "date-tag=$(date +'%Y-%m')" >> $GITHUB_OUTPUT
          JSON_DATA=`cat ./config.json`
          JSON_DATA="${JSON_DATA//'%'/'%25'}"
          JSON_DATA="${JSON_DATA//$'\n'/'%0A'}"
          JSON_DATA="${JSON_DATA//$'\r'/'%0D'}"
          echo "matrix={\"include\": $JSON_DATA }"
          echo "matrix={\"include\": $JSON_DATA }" >> $GITHUB_OUTPUT
      - id: create-release
        name: ${{ steps.setup.outputs.date-tag }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.setup.outputs.date-tag }}
          name: ${{ steps.setup.outputs.date-tag }}


  build-archives:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: release
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.release.outputs.matrix) }}
    name: build-${{ matrix.name }}
    steps:
      - run: mkdir /tmp/output
      - id: build-archive
        run: docker run -v /tmp/output:/output --shm-size=1gb ghcr.io/openzim/zimit zimit --url ${{ matrix.url }} --name ${{ matrix.name }} --lang ${{ matrix.lang }} --title ${{ matrix.title }} --description "${{ matrix.desc }}" --source "https://github.com/f0sh/kiwix-library" --creator f0sh --workers 4 --waitUntil domcontentloaded
      - id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.date-tag }}
          files: /tmp/output/*.zim