name: Archive

on:
  schedule:
    - cron: "0 0 1 * *" # run every first of month
  workflow_dispatch:
  push:
    
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      date-tag: ${{ steps.set.outputs.date-tag }}
    steps:
      - id: set
        run: echo "date-tag=$(date +'%Y-%m')" >> $GITHUB_OUTPUT
      - id: create-release
        name: ${{ steps.set.outputs.date-tag }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set.outputs.date-tag }}
          name: ${{ steps.set.outputs.date-tag }}


  build-archives:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: release
    strategy:
      matrix:
        include:
          - url: "https://go.dev/doc/"
            name: "go-docs"
          - url: "https://go.dev/learn/"
            name: "learn-go"
          - url: "https://docs.codeberg.org/"
            name: "codeberg-docs"
          - url: "https://docs.python.org"
            name: "python-docs"
          - url: "https://python-telegram-bot.readthedocs.io/"
            name: "python-telegram-bot-docs"
          - url: "https://gohugo.io/documentation/"
            name: "hugo-docs"
    steps:
      - uses: actions/checkout@v3
      - run: mkdir /tmp/output
      - id: build-archive
        run: docker run -v /tmp/output:/output --shm-size=1gb ghcr.io/openzim/zimit zimit --url ${{ matrix.url }} --name ${{ matrix.name }} --workers 4 --waitUntil domcontentloaded
      - id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.date-tag }}
          files: /tmp/output/*.zim