name: Archive

on:
  schedule:
    - cron: "0 0 1 * *" # run every first of month

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      release_id: ${{ steps.create-release.outputs.id }}
    steps:
      - id: set-date-tag
        run: echo "date-tag=$(date +'%Y-%m')" >> $GITHUB_OUTPUT
      - id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set-date-tag.output.date-tag}}
          release_name: ${{ steps.set-date-tag.output.date-tag}}


  build-archives:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        include:
          - url: "https://go.dev/doc/"
            name: "go-docs"
          - url: "https://go.dev/learn/"
            name: "learn-go"
          - url: "https://docs.codeberg.org/"
            name: "codeberg-docs"
          - url: "https://docs.python.org"
            name: "python-docs"
          - url: "https://python-telegram-bot.readthedocs.io/"
            name: "python-telegram-bot-docs"
          - url: "https://gohugo.io/documentation/"
            name: "hugo-docs"
    steps:
      - uses: actions/checkout@v3
      - run: mkdir /tmp/output
      - run: docker run -v /tmp/output:/output --shm-size=1gb ghcr.io/openzim/zimit zimit --url ${{ matrix.url }} --name ${{ matrix.name }} --workers 4 --waitUntil domcontentloaded
        id: build-archive
      - uses: actions/upload-artifact@v3 # TODO: can be deleted once releases are working
        with:
          name: ${{ matrix.name }}
          path: /tmp/output/*.zim
      - id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: /tmp/output/*.zim